version: '3.9'

services:
  frontend:
    container_name: app_frontend    
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend
    networks:
      - crawler_web_net

  backend:
    build: ./backend
    image: crawler_web
    platform: linux/x86_64
    volumes:
      - ./backend:/app
    container_name: crawler_web_backend
    tty: true # docker run -t 
    stdin_open: true # docker run -i
    command: bash
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
    networks:
      - crawler_web_net
    ports:
      - 8000:8000

  mongodb:
    image: mongo:5.0.6
    container_name: crawler_web_db
    volumes:
      - ./:/app
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - crawler_web_net

networks:
  crawler_web_net:
    driver: bridge
